import type { Resource, Comment } from '@/types/resource';
import type { Announcement } from '@/types/announcement';

export const mockResources: Omit<Resource, 'source' | 'source_url'>[] = [
  {
    id: 1,
    name: 'Quranic Text Toolkit (QTT)',
    slug: 'quranic-text-toolkit',
    type: 'library',
    description: 'A comprehensive Python library for processing, analyzing, and rendering Quranic Arabic text. Supports Uthmani script, simple script, and Indopak variants. Includes word-by-word segmentation and morphological analysis.',
    short_description: 'Python library for processing and analyzing Quranic Arabic text with morphological analysis.',
    documentation_url: 'https://github.com/example/quranic-text-toolkit',
    github_url: 'https://github.com/example/quranic-text-toolkit',
    license: 'MIT',
    itqan_badge: true,
    status: 'published',
    created_at: '2025-06-15T10:00:00Z',
    updated_at: '2026-01-20T14:30:00Z',
    version: 'v2.4.1',
    github_stats: { stars: 342, forks: 58, open_issues: 7, last_commit: '2026-04-20T10:30:00Z' },
    consumers: [
      { name: 'Quran.com', website_url: 'https://quran.com', category: 'Website' },
      { name: 'iSalam', website_url: 'https://isalam.app', category: 'Mobile App' },
      { name: 'Ayat', website_url: 'https://ayat.app', category: 'Mobile App' },
      { name: 'Noor App', website_url: 'https://noor.app', category: 'Mobile App' },
      { name: 'Quran+ AI', website_url: 'https://quranplus.io', category: 'AI Platform' },
      { name: 'Al-Maktaba', website_url: 'https://maktaba.org', category: 'E-Book' },
      { name: 'Quranic NLP', website_url: 'https://qurannlp.org', category: 'Research' },
      { name: 'PrayerTime', website_url: 'https://prayertime.app', category: 'Utility' },
    ],
    total_downloads: 12450,
    downloads: 2840,
  },
  {
    id: 2,
    name: 'Surah Navigator SDK',
    slug: 'surah-navigator-sdk',
    type: 'sdk',
    description: 'Cross-platform mobile SDK for building Quran navigation experiences. Features Surah/Ayah browsing, bookmarks, recitation sync, and tafsir integration. Works on iOS, Android, and React Native.',
    short_description: 'Cross-platform SDK for Quran navigation with bookmarks and recitation sync.',
    documentation_url: 'https://docs.example.com/surah-navigator',
    github_url: 'https://github.com/example/surah-navigator-sdk',
    license: 'Apache-2.0',
    itqan_badge: true,
    status: 'published',
    created_at: '2025-08-10T09:00:00Z',
    updated_at: '2026-02-15T11:00:00Z',
    version: 'v1.8.0',
    github_stats: { stars: 215, forks: 34, open_issues: 3, last_commit: '2026-04-25T08:15:00Z' },
    consumers: [
      { name: 'iSalam', website_url: 'https://isalam.app', category: 'Mobile App' },
      { name: 'Ayat', website_url: 'https://ayat.app', category: 'Mobile App' },
      { name: 'VerseMap', website_url: 'https://versemap.io', category: 'Analytics' },
    ],
    total_downloads: 8930,
    downloads: 1920,
  },
  {
    id: 3,
    name: 'Classical Arabic Morphology Dataset',
    slug: 'classical-arabic-morphology-dataset',
    type: 'dataset',
    description: 'A labeled dataset of 50,000+ Quranic words with full Arabic morphological parsing: root, pattern, part of speech, case ending (i\'rab), and derivation. Annotated by scholars trained in traditional Arabic grammar.',
    short_description: '50,000+ Quranic words with full Arabic morphological parsing and case endings.',
    documentation_url: null,
    github_url: 'https://github.com/example/arabic-morphology-dataset',
    license: 'CC-BY-SA-4.0',
    itqan_badge: true,
    status: 'published',
    created_at: '2025-03-22T08:00:00Z',
    updated_at: '2025-12-01T16:00:00Z',
    version: 'v3.0.0',
    github_stats: { stars: 189, forks: 42, open_issues: 12, last_commit: '2026-04-10T14:00:00Z' },
    consumers: [
      { name: 'Quranic NLP', website_url: 'https://qurannlp.org', category: 'Research' },
      { name: 'ArabicKit', website_url: 'https://arabickit.dev', category: 'Toolkit' },
    ],
    total_downloads: 6720,
    downloads: 1560,
  },
  {
    id: 4,
    name: 'Quranic Search API',
    slug: 'quranic-search-api',
    type: 'api',
    description: 'RESTful search API for the Quran text with full-text search, fuzzy matching, word-level indexing, and multilingual query support (Arabic, English, Urdu). Returns verse-level results with contextual highlighting.',
    short_description: 'RESTful API for full-text Quran search with multilingual query support.',
    documentation_url: 'https://api.example.com/quran-search/docs',
    github_url: null,
    license: 'custom',
    itqan_badge: false,
    status: 'published',
    created_at: '2025-11-05T12:00:00Z',
    updated_at: '2026-03-10T09:00:00Z',
    version: null,
    github_stats: null,
    consumers: [
      { name: 'Quran.com', website_url: 'https://quran.com', category: 'Website' },
      { name: 'VerseAnalytics', website_url: 'https://verseanalytics.io', category: 'Analytics' },
    ],
    total_downloads: 15200,
    downloads: 1240,
  },
  {
    id: 5,
    name: 'Tafsir Ibn Kathir Digital Corpus',
    slug: 'tafsir-ibn-kathir-corpus',
    type: 'tafsir',
    description: 'Digitized, searchable corpus of Tafsir Ibn Kathir in Arabic with verse-level alignment. Includes cross-references to hadith sources, chain of narration metadata, and searchable index of legal rulings.',
    short_description: 'Searchable Tafsir Ibn Kathir corpus with hadith cross-references.',
    documentation_url: null,
    github_url: 'https://github.com/example/tafsir-ibn-kathir-corpus',
    license: 'GPL-3.0',
    itqan_badge: true,
    status: 'published',
    created_at: '2025-01-18T10:00:00Z',
    updated_at: '2026-02-28T14:00:00Z',
    version: 'v1.2.3',
    github_stats: { stars: 421, forks: 67, open_issues: 2, last_commit: '2026-04-22T09:45:00Z' },
    consumers: [],
    total_downloads: 18340,
    downloads: 980,
  },
  {
    id: 6,
    name: 'Arabic Font Rendering Engine',
    slug: 'arabic-font-rendering-engine',
    type: 'library',
    description: 'High-performance Arabic calligraphy rendering engine with support for traditional Quranic fonts (Uthmani Taha, Madinah, Indopak). Handles contextual glyph shaping, ligature optimization, and RTL layout.',
    short_description: 'Arabic calligraphy renderer for traditional Quranic fonts with RTL layout.',
    documentation_url: 'https://docs.example.com/arabic-renderer',
    github_url: 'https://github.com/example/arabic-font-renderer',
    license: 'MIT',
    itqan_badge: false,
    status: 'published',
    created_at: '2025-07-30T11:00:00Z',
    updated_at: '2026-01-05T10:00:00Z',
    version: 'v1.0.5',
    github_stats: null,
    consumers: [],
    total_downloads: 4100,
    downloads: 750,
  },
  {
    id: 7,
    name: 'Quranic Audio SDK',
    slug: 'quranic-audio-sdk',
    type: 'sdk',
    description: 'SDK for embedding Quranic recitation in applications. Supports multiple qaris (Al-Afasy, Abdul-Rahman Al-Sudais, Mishary Rashid), verse-level sync, and offline caching. Works with web and mobile platforms.',
    short_description: 'Embed Quranic recitations with verse-level sync and offline caching.',
    documentation_url: 'https://docs.example.com/quranic-audio-sdk',
    github_url: 'https://github.com/example/quranic-audio-sdk',
    license: 'BSD-3-Clause',
    itqan_badge: true,
    status: 'published',
    created_at: '2025-09-14T08:00:00Z',
    updated_at: '2026-03-01T12:00:00Z',
    version: 'v2.1.0',
    github_stats: { stars: 156, forks: 23, open_issues: 5, last_commit: '2026-04-18T16:20:00Z' },
    consumers: [],
    total_downloads: 9870,
    downloads: 620,
  },
  {
    id: 8,
    name: 'Quranic Translation Alignment Dataset',
    slug: 'quranic-translation-alignment-dataset',
    type: 'dataset',
    description: 'Verse-aligned parallel corpus covering 12 major translations (English, Urdu, Indonesian, Turkish, French, German, Spanish, Malay, Bengali, Persian, Swahili, Chinese). Includes transliteration and back-translation data.',
    short_description: 'Verse-aligned parallel corpus of 12 Quran translations with transliteration.',
    documentation_url: null,
    github_url: 'https://github.com/example/quranic-translation-alignment',
    license: 'CC-BY-4.0',
    itqan_badge: true,
    status: 'published',
    created_at: '2025-04-05T09:00:00Z',
    updated_at: '2026-02-10T15:00:00Z',
    version: null,
    github_stats: { stars: 95, forks: 18, open_issues: 4, last_commit: '2026-04-15T12:30:00Z' },
    consumers: [],
    total_downloads: 5430,
    downloads: 480,
  },
  {
    id: 9,
    name: 'Verse-by-Verse Analytics API',
    slug: 'verse-analytics-api',
    type: 'api',
    description: 'API providing verse-level metadata including word count, recurring keywords, thematic classification, and cross-reference links. Integrates with NLP pipelines for semantic analysis and pattern detection.',
    short_description: 'Verse-level metadata API with keywords, themes, and cross-references.',
    documentation_url: 'https://api.example.com/verse-analytics/docs',
    github_url: null,
    license: 'custom',
    itqan_badge: false,
    status: 'published',
    created_at: '2025-12-01T10:00:00Z',
    updated_at: '2026-03-15T08:00:00Z',
    version: null,
    github_stats: null,
    consumers: [],
    total_downloads: 7650,
    downloads: 350,
  },
  {
    id: 10,
    name: 'Majid Al-Hudhaify Tafsir Digital',
    slug: 'majid-al-hudhaify-tafsir',
    type: 'tafsir',
    description: 'Digital collection of Tafsir Al-Muyassar (Majid) with Arabic text, word-by-word translation, and legal rulings. Structured JSON format optimized for programmatic access and display.',
    short_description: 'Tafsir Al-Muyassar in structured JSON with word-by-word translation.',
    documentation_url: null,
    github_url: 'https://github.com/example/majid-tafsir-digital',
    license: 'CC-BY-NC-4.0',
    itqan_badge: false,
    status: 'published',
    created_at: '2025-10-20T14:00:00Z',
    updated_at: '2026-01-15T11:00:00Z',
    version: null,
    github_stats: null,
    consumers: [],
    total_downloads: 3200,
    downloads: 290,
  },
  {
    id: 11,
    name: 'Quranic Keyword Extractor',
    slug: 'quranic-keyword-extractor',
    type: 'library',
    description: 'NLP library for extracting and analyzing recurring keywords in the Quran. Provides frequency analysis, co-occurrence graphs, thematic clustering, and semantic similarity scoring between verses.',
    short_description: 'NLP library for keyword extraction and thematic analysis of Quranic text.',
    documentation_url: 'https://docs.example.com/keyword-extractor',
    github_url: 'https://github.com/example/quranic-keyword-extractor',
    license: 'MIT',
    itqan_badge: false,
    status: 'published',
    created_at: '2026-01-10T09:00:00Z',
    updated_at: '2026-03-20T10:00:00Z',
    version: null,
    github_stats: null,
    total_downloads: 2100,
    downloads: 210,
  },
  {
    id: 12,
    name: 'Web Quran Reader SDK',
    slug: 'web-quran-reader-sdk',
    type: 'sdk',
    description: 'Lightweight JavaScript SDK for building web-based Quran readers. Features Surah navigation, bookmarks, highlighting, copy-to-clipboard, and responsive RTL layout. Zero dependencies.',
    short_description: 'Lightweight JS SDK for web-based Quran readers with zero dependencies.',
    documentation_url: 'https://docs.example.com/web-quran-reader',
    github_url: 'https://github.com/example/web-quran-reader-sdk',
    license: 'MIT',
    itqan_badge: true,
    status: 'published',
    created_at: '2025-05-25T08:00:00Z',
    updated_at: '2026-02-05T14:00:00Z',
    version: 'v4.0.2',
    github_stats: { stars: 278, forks: 45, open_issues: 1, last_commit: '2026-04-26T11:00:00Z' },
    consumers: [],
    total_downloads: 11200,
    downloads: 180,
  },
  {
    id: 13,
    name: 'Quranic Recitation Audio Dataset',
    slug: 'quranic-recitation-audio-dataset',
    type: 'dataset',
    description: 'Complete audio dataset of 7 canonical Quranic recitations (Qira\'at) with verse-level timestamps and metadata. Includes Al-Afasy, Abdulrahman Al-Sudais, Mahmoud Khalil Al-Hussary, and others.',
    short_description: '7 canonical Quranic recitations with verse-level timestamps and metadata.',
    documentation_url: null,
    github_url: 'https://github.com/example/quranic-audio-dataset',
    license: 'CC-BY-4.0',
    itqan_badge: false,
    status: 'published',
    created_at: '2025-06-01T10:00:00Z',
    updated_at: '2026-01-25T09:00:00Z',
    version: null,
    github_stats: { stars: 134, forks: 29, open_issues: 8, last_commit: '2026-04-12T10:00:00Z' },
    consumers: [],
    total_downloads: 4890,
    downloads: 145,
  },
  {
    id: 14,
    name: 'Tajweed Rules API',
    slug: 'tajweed-rules-api',
    type: 'api',
    description: 'API for applying Tajweed rules to Quranic text. Returns phonetic classification (Idgham, Iqlab, Ikhfa, Madd) for each word segment, color-coded output for visualization, and rule explanation metadata.',
    short_description: 'Apply Tajweed rules to Quranic text with color-coded output.',
    documentation_url: 'https://api.example.com/tajweed/docs',
    github_url: null,
    license: 'custom',
    itqan_badge: false,
    status: 'published',
    created_at: '2026-02-01T11:00:00Z',
    updated_at: '2026-03-18T13:00:00Z',
    version: null,
    github_stats: null,
    consumers: [],
    total_downloads: 3450,
    downloads: 98,
  },
  {
    id: 15,
    name: 'Imam Al-Baghawi Tafsir Digital',
    slug: 'imam-baghawi-tafsir',
    type: 'tafsir',
    description: 'Digitized Tafsir Al-Baghawi (Ma\'ālim al-Tanzīl) in structured JSON format. Includes verse-level commentary, hadith references, scholarly opinions, and linguistic analysis. Full-text searchable.',
    short_description: 'Tafsir Al-Baghawi in structured JSON with hadith references and analysis.',
    documentation_url: null,
    github_url: 'https://github.com/example/baghawi-tafsir-digital',
    license: 'GPL-3.0',
    itqan_badge: true,
    status: 'published',
    created_at: '2025-02-14T10:00:00Z',
    updated_at: '2026-02-20T16:00:00Z',
    version: null,
    github_stats: { stars: 203, forks: 38, open_issues: 6, last_commit: '2026-04-19T15:45:00Z' },
    consumers: [],
    total_downloads: 7120,
    downloads: 72,
  },
  {
    id: 16,
    name: 'Quranic Arabic Corpus',
    slug: 'quranic-arabic-corpus',
    type: 'library',
    description: 'Annotated corpus of the Quranic Arabic text with full syntactic parsing, morphological analysis, and lemmatization. Based on the published Quranic Arabic Corpus project by Dr. Alexander Lubowski.',
    short_description: 'Annotated Quranic Arabic corpus with syntactic parsing and lemmatization.',
    documentation_url: 'http://qurancodepus.org',
    github_url: 'https://github.com/example/quranic-arabic-corpus',
    license: 'CC-BY-SA-3.0',
    itqan_badge: true,
    status: 'published',
    created_at: '2024-11-08T09:00:00Z',
    updated_at: '2025-12-20T10:00:00Z',
    version: null,
    github_stats: { stars: 512, forks: 89, open_issues: 15, last_commit: '2026-04-24T08:00:00Z' },
    consumers: [],
    total_downloads: 21500,
    downloads: 45,
  },
  {
    id: 17,
    name: 'Quranic Verse Mapping SDK',
    slug: 'quranic-verse-mapping-sdk',
    type: 'sdk',
    description: 'SDK for visualizing Quranic verse relationships and thematic connections. Creates interactive network graphs showing keyword co-occurrence, thematic clustering, and cross-references between verses and Surahs.',
    short_description: 'Visualize verse relationships and thematic connections with interactive graphs.',
    documentation_url: 'https://docs.example.com/verse-mapping',
    github_url: 'https://github.com/example/verse-mapping-sdk',
    license: 'MIT',
    itqan_badge: false,
    status: 'published',
    created_at: '2025-08-20T12:00:00Z',
    updated_at: '2026-01-30T08:00:00Z',
    version: null,
    github_stats: null,
    total_downloads: 2870,
    downloads: 30,
  },
  {
    id: 18,
    name: 'Parallel Translation Corpus',
    slug: 'parallel-translation-corpus',
    type: 'dataset',
    description: 'Multi-translation parallel corpus of the Quran in 15 languages with verse-aligned formatting. Includes original Arabic text, translator names, and translation metadata. Ideal for ML/NLP training.',
    short_description: 'Quran parallel corpus in 15 languages, verse-aligned for ML/NLP training.',
    documentation_url: null,
    github_url: 'https://github.com/example/parallel-translation-corpus',
    license: 'CC-BY-4.0',
    itqan_badge: true,
    status: 'published',
    created_at: '2025-04-15T09:00:00Z',
    updated_at: '2026-03-05T14:00:00Z',
    version: null,
    github_stats: { stars: 167, forks: 31, open_issues: 3, last_commit: '2026-04-21T13:15:00Z' },
    total_downloads: 6340,
    downloads: 18,
  },
  {
    id: 19,
    name: 'Quranic Bilingual Search API',
    slug: 'quranic-bilingual-search-api',
    type: 'api',
    description: 'Bilingual (Arabic-English) search API for Quranic content. Supports semantic search, keyword matching, and verse-level result highlighting. Returns results ranked by relevance with context snippets.',
    short_description: 'Arabic-English search API for Quranic content with semantic matching.',
    documentation_url: 'https://api.example.com/bilingual-search/docs',
    github_url: null,
    license: 'custom',
    itqan_badge: false,
    status: 'published',
    created_at: '2026-01-25T10:00:00Z',
    updated_at: '2026-03-22T11:00:00Z',
    version: null,
    github_stats: null,
    total_downloads: 5120,
    downloads: 12,
  },
  {
    id: 20,
    name: 'Al-Jalalayn Tafsir Digital',
    slug: 'al-jalalayn-tafsir',
    type: 'tafsir',
    description: 'Digitized Tafsir Al-Jalalayn (Jalal ad-Din al-Mahalli and Jalal ad-Din as-Suyuti) with Arabic text and English translation. Structured verse-by-verse, optimized for mobile display and offline access.',
    short_description: 'Tafsir Al-Jalalayn with Arabic text and English translation, verse-by-verse.',
    documentation_url: null,
    github_url: 'https://github.com/example/al-jalalayn-digital',
    license: 'MIT',
    itqan_badge: false,
    status: 'published',
    created_at: '2025-07-08T11:00:00Z',
    updated_at: '2026-02-12T09:00:00Z',
    version: null,
    github_stats: null,
    total_downloads: 4560,
    downloads: 5,
  },
];

export const mockComments: Record<number, Comment[]> = {
  1: [
    {
      id: 1,
      author_name: 'Ahmad K.',
      content: 'Excellent library! The morphological analysis module has been incredibly useful for our research project. The documentation could use more examples though.',
      created_at: '2026-01-15T14:30:00Z',
    },
    {
      id: 2,
      author_name: 'Sarah M.',
      content: 'We\'ve integrated this into our Quranic study app. Works perfectly for word-level segmentation. Would love to see support for Indopak script added.',
      created_at: '2026-02-03T09:15:00Z',
    },
  ],
  2: [
    {
      id: 3,
      author_name: 'Omar H.',
      content: 'The SDK is very well-structured. Cross-platform support is a huge plus. The recitation sync feature is particularly polished.',
      created_at: '2026-02-20T16:45:00Z',
    },
  ],
  3: [
    {
      id: 4,
      author_name: 'Dr. Yusuf B.',
      content: 'This dataset is a goldmine for NLP research. The morphological annotations are accurate and well-labeled. Used it for my dissertation on Arabic NLP.',
      created_at: '2025-11-10T11:20:00Z',
    },
    {
      id: 5,
      author_name: 'Fatima R.',
      content: 'Thank you for the careful annotations. The case ending (i\'rab) data is particularly valuable.',
      created_at: '2025-12-05T08:00:00Z',
    },
  ],
  5: [
    {
      id: 6,
      author_name: 'Abdullah S.',
      content: 'The hadith cross-references are well-organized and make it easy to verify the sources. A must-have for serious tafsir study.',
      created_at: '2026-01-25T10:00:00Z',
    },
  ],
  8: [
    {
      id: 7,
      author_name: 'Lisa W.',
      content: '12 translations aligned at the verse level is incredible. Perfect for my comparative translation research. The quality of alignment is surprisingly good.',
      created_at: '2026-02-01T13:00:00Z',
    },
  ],
};

export const mockPaginated = <T>(items: T[], pageSize: number, page: number) => {
  const start = (page - 1) * pageSize;
  const end = start + pageSize;
  return {
    count: items.length,
    next: end < items.length ? `/api/v1/resources/?page=${page + 1}` : null,
    previous: page > 1 ? `/api/v1/resources/?page=${page - 1}` : null,
    results: items.slice(start, end),
  };
};

export const mockAnnouncements: Announcement[] = [
  {
    id: '1',
    type: 'release',
    title: 'Quran API v2.1 Released',
    description: 'New endpoints for surah-level search and improved translation matching.',
    resource_id: 'quran-api',
    cta_url: '/resources/quran-api',
    cta_label: 'View resource',
    created_at: '2026-04-28T10:00:00Z',
    is_active: true,
  },
  {
    id: '2',
    type: 'new_resource',
    title: 'New: Quranic Text Toolkit (QTT) SDK',
    description: 'A comprehensive SDK for Quranic text processing and analysis.',
    resource_id: 'quranic-text-toolkit',
    cta_url: '/resources/quranic-text-toolkit',
    cta_label: 'View resource',
    created_at: '2026-04-27T14:30:00Z',
    is_active: true,
  },
  {
    id: '3',
    type: 'maintenance',
    title: 'Scheduled Maintenance: April 30',
    description: 'Platform maintenance from 2:00 AM to 4:00 AM UTC. Expect brief downtime.',
    created_at: '2026-04-26T08:00:00Z',
    expires_at: '2026-04-30T04:00:00Z',
    is_active: true,
  },
  {
    id: '4',
    type: 'breaking_change',
    title: 'API v1 Deprecation Notice',
    description: 'API v1 will be retired on June 1, 2026. Migrate to v2 endpoints.',
    created_at: '2026-04-25T09:00:00Z',
    expires_at: '2026-06-01T00:00:00Z',
    is_active: true,
  },
  {
    id: '5',
    type: 'release',
    title: 'Arabic NLP Dataset v1.0',
    description: 'New annotated dataset for Arabic Quranic text classification.',
    resource_id: 'arabic-nlp-dataset',
    cta_url: '/resources/arabic-nlp-dataset',
    cta_label: 'View resource',
    created_at: '2026-04-24T12:00:00Z',
    is_active: true,
  },
  {
    id: '6',
    type: 'new_resource',
    title: 'New: Tafsir Ibn Kathir Digital Edition',
    description: 'Complete digital edition of Tafsir Ibn Kathir with search and cross-references.',
    resource_id: 'tafsir-ibn-kathir',
    cta_url: '/resources/tafsir-ibn-kathir',
    cta_label: 'View resource',
    created_at: '2026-04-23T16:00:00Z',
    is_active: true,
  },
];
