import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

// Generated by `payload migrate:create`, kept as generated. One behaviour is
// worth knowing before anyone runs it: down() recreates the enum without
// 'revoked', so it fails with `invalid input value for enum
// enum_access_requests_status: "revoked"` if any request has actually been
// revoked by then. Verified against a real database - the failure is atomic,
// Postgres rolls the whole statement back and the enum, the rows and the
// migration record are all left untouched.
//
// That is deliberately not smoothed over. The only way to make down() succeed
// with live data is to rewrite those rows first, and every option is worse
// than failing: mapping revoked -> approved silently hands back access a
// publisher deliberately removed, and revoked -> denied rewrites history into
// a state the applicant was never notified about. Rolling this back once
// access has been revoked is a call for a human to make explicitly.
export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   ALTER TYPE "public"."enum_access_requests_status" ADD VALUE 'revoked';`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   ALTER TABLE "access_requests" ALTER COLUMN "status" SET DATA TYPE text;
  ALTER TABLE "access_requests" ALTER COLUMN "status" SET DEFAULT 'pending'::text;
  DROP TYPE "public"."enum_access_requests_status";
  CREATE TYPE "public"."enum_access_requests_status" AS ENUM('pending', 'approved', 'denied');
  ALTER TABLE "access_requests" ALTER COLUMN "status" SET DEFAULT 'pending'::"public"."enum_access_requests_status";
  ALTER TABLE "access_requests" ALTER COLUMN "status" SET DATA TYPE "public"."enum_access_requests_status" USING "status"::"public"."enum_access_requests_status";`)
}
